[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "react"
  command = "npm start"
  port = 3000
  targetPort = 3000
  publish = "build"